package com.aura.error;

public enum AuraErrorCode {
    VALIDATION_ERROR,
    SESSION_NOT_FOUND,
    OLLAMA_EMPTY_RESPONSE,
    INTERNAL_ERROR,
    OLLAMA_UNREACHABLE,
    AUTH_INVALID_CREDENTIALS,
    AUTH_REFRESH_INVALID,
    AUTH_REFRESH_REVOKED,
    AUTH_REFRESH_EXPIRED,
    USER_ALREADY_EXISTS,
    FORBIDDEN,
    INVALID_FILE_TYPE,
    FILE_TOO_LARGE,
    PDF_ENCRYPTED,
    PDF_TOO_MANY_PAGES,
    PDF_PARSE_FAILED
}
